import { LineEdit } from "std-widgets.slint";
export component HelloWorld {
    in property<string> clock_text;
    in property<bool> checking_password;
    in-out property<string> password <=> password.text;
    callback submit <=> password.accepted;
    forward-focus: password;
    states [
        checking when checking-password : {
            password.enabled: false;
        }
    ]

    Image {
        width: parent.width;
        height: parent.height;
        source: @image-url("./wallpaper.jpg");
        HorizontalLayout {
            VerticalLayout {
                alignment: end;
                spacing: 10px;
                padding: 40px;
                width: 350px;
                Text {
                    text: clock_text;
                    horizontal-alignment: center;
                    font-size: 60pt;
                    color: white;
                }
                password := LineEdit {
                    enabled: true;
                    horizontal-alignment: left;
                    input-type: InputType.password;
                    placeholder-text: "password...";
                }
            }
        }
    }
}
