[package]
name = "cthulock"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
env_logger = "0.10.1"
futures = "0.3.29"
glutin = "0.31.1"
image = "0.24.7"
khronos-egl = { version = "6.0.0", features = ["static"] }
log = "0.4.20"
pam-client = "0.5.0"
raw-window-handle = "0.5"
slint = { version = "1.3.2", default-features = false, features = ["renderer-femtovg", "std", "compat-1-2", "renderer-software"] }
slint-interpreter = { version = "1.3.2", features = ["display-diagnostics"]}
smithay-client-toolkit = "0.18.0"
tempfile = "3.8.1"
thiserror = "1.0.50"
wayland-client = "0.31.1"
wayland-egl = "0.32.0"
wayland-protocols = { version = "0.31.0", features = ["client", "staging"] }
whoami = "1.4.1"
xdg = "2.5.2"

