[package]
name = "cthulock"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
glutin = "0.31.1"
khronos-egl = { version = "6.0.0", features = ["static"] }
raw-window-handle = "0.5"
slint = { version = "1.3.0", default-features = false, features = ["renderer-femtovg", "std", "compat-1-2", "renderer-software"] }
smithay-client-toolkit = "0.18.0"
tempfile = "3.8.1"
wayland-client = "0.31.1"
wayland-egl = "0.32.0"
wayland-protocols = { version = "0.31.0", features = ["client", "staging"] }

